language: node_js
sudo: required
services:
  - rabbitmq
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '10'
before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
before_script:
  - npm prune
  - greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
