language: node_js
sudo: required
services:
  - docker
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '6'
before_install:
  - 'docker pull rabbitmq:management'
  - './test/bin/rabbit'
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
