language: node_js
sudo: required
services:
  - rabbitmq
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '6'
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
